import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:liveview_flutter/live_view/state/element_key.dart';
import 'package:liveview_flutter/live_view/ui/components/live_form.dart';
import 'package:liveview_flutter/live_view/ui/components/state_widget.dart';
import 'package:uuid/uuid.dart';
import 'package:xml/xml.dart';

/// A currency form input, usable like any other field inside a `<Form>`:
///
/// ```xml
/// <CurrencyInput name="user[default_currency]" initialValue="EUR"
///                label="Change currency" hint="Search a currency...">
///   <Option value="EUR" label="EUR (€) — Euro" flag="/images/flags/EUR.png" />
///   <Option value="USD" label="USD ($) — US Dollar" flag="/images/flags/USD.png" />
/// </CurrencyInput>
/// ```
///
/// Shows the selected currency in a tappable field; tapping opens a dropdown
/// floating over the content with a client-side search. Selecting an option
/// dispatches a form change event with the option's value, exactly like the
/// other inputs.
class LiveCurrencyInput extends LiveStateWidget<LiveCurrencyInput> {
  const LiveCurrencyInput({super.key, required super.state});

  @override
  State<LiveCurrencyInput> createState() => _LiveCurrencyInputState();
}

class _LiveCurrencyInputState extends StateWidget<LiveCurrencyInput> {
  final attributes = ['name', 'initialValue', 'label', 'hint', 'emptyLabel'];
  final childAttributes = ['value', 'label', 'flag'];

  final _link = LayerLink();
  final _targetKey = GlobalKey();
  final _overlayController = OverlayPortalController();
  final _searchController = TextEditingController();

  var unamedInput = const Uuid().v4();
  bool allowInitialValueChange = true;
  String? currentValue;
  String _query = '';
  double? _overlayWidth;

  @override
  handleClickState() => HandleClickState.manual;

  String get fieldName =>
      getAttribute('name') ?? 'unamed-currency-input-$unamedInput';

  @override
  void initState() {
    Future.delayed(Duration.zero, () {
      sendInitialFormState();
    });
    super.initState();
  }

  @override
  void onWipeState() {
    allowInitialValueChange = true;
    super.onWipeState();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  void sendInitialFormState() {
    reloadAttributes(node, attributes);
    FormFieldEvent(
      name: fieldName,
      data: getAttribute('initialValue'),
      type: FormFieldEventType.initField,
    ).dispatch(context);
  }

  @override
  void onStateChange(Map<String, dynamic> diff) {
    reloadAttributes(node, attributes);
    if (allowInitialValueChange) {
      allowInitialValueChange = false;
      currentValue = getAttribute('initialValue');
    }
  }

  List<Map<String, String?>> get currencies =>
      _optionNodes()
          .map(
            (option) => bindChildVariableAttributes(option, [
              ...childAttributes,
            ], widget.state.variables),
          )
          .toList();

  /// Collects the `<Option>` children, including the ones generated by a
  /// server-side `:for` loop: those arrive as a `[[flutterState key=N]]`
  /// text placeholder whose rows live in the template variables ('s' statics
  /// interleaved with each 'd' row), not as real XML children.
  List<XmlNode> _optionNodes() {
    var options = childrenNodesOf(node, 'Option');
    var placeholder = RegExp(
      r'\[\[flutterState\s*key=(\d+)(?:\s+component=\d+)?\]\]',
    );

    for (var child in node.children) {
      if (child.nodeType != XmlNodeType.TEXT) {
        continue;
      }
      var match = placeholder.firstMatch(child.toString());
      if (match == null) {
        continue;
      }

      addListenedKey(ElementKey(match.group(1)!));
      var dynamic = widget.state.variables[match.group(1)];
      if (dynamic is! Map) {
        continue;
      }

      var statics = List<String>.from(dynamic['s'] ?? []);
      var rows = dynamic['d'];
      if (statics.isEmpty || rows is! List) {
        continue;
      }

      for (var row in rows) {
        var buffer = StringBuffer();
        for (var i = 0; i < statics.length; i++) {
          buffer.write(statics[i]);
          if (i < row.length) {
            buffer.write(row[i]);
          }
        }
        options.addAll(
          childrenNodesOf(
            XmlDocumentFragment.parse(buffer.toString()),
            'Option',
          ),
        );
      }
    }

    return options;
  }

  Map<String, String?>? get selected {
    for (var currency in currencies) {
      if (currency['value'] == currentValue) {
        return currency;
      }
    }
    return null;
  }

  List<Map<String, String?>> get filteredCurrencies {
    var query = _query.toLowerCase().trim();
    if (query.isEmpty) {
      return currencies;
    }
    return currencies.where((currency) {
      return (currency['label'] ?? '').toLowerCase().contains(query) ||
          (currency['value'] ?? '').toLowerCase().contains(query);
    }).toList();
  }

  void _select(Map<String, String?> currency) {
    setState(() {
      currentValue = currency['value'];
      _query = '';
      _searchController.clear();
    });
    _overlayController.hide();
    FormFieldEvent(
      name: fieldName,
      data: currentValue,
      type: FormFieldEventType.change,
    ).dispatch(context);
  }

  /// The overlay entry builds during the same frame as the trigger, before
  /// layout, so the target width is read after the frame and cached.
  void _measureTriggerWidth() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      var renderObject = _targetKey.currentContext?.findRenderObject();
      if (renderObject is! RenderBox ||
          !renderObject.attached ||
          !renderObject.hasSize) {
        return;
      }
      var width = renderObject.size.width;
      if (mounted && width != _overlayWidth) {
        setState(() => _overlayWidth = width);
      }
    });
  }

  Widget _flag(String? flag, {double width = 32, double height = 24}) {
    if (flag == null) {
      return SizedBox(width: width, height: height);
    }
    var url = flag;
    if (!url.startsWith('http')) {
      url =
          Uri.parse(
            '${liveView.endpointScheme}://${liveView.host}',
          ).resolve(url).toString();
    }
    return CachedNetworkImage(
      imageUrl: url,
      width: width,
      height: height,
      errorWidget: (_, _, _) => SizedBox(width: width, height: height),
    );
  }

  @override
  Widget render(BuildContext context) {
    var selectedCurrency = selected;
    var filtered = filteredCurrencies;

    return OverlayPortal(
      controller: _overlayController,
      overlayChildBuilder: (context) {
        _measureTriggerWidth();
        return CompositedTransformFollower(
          link: _link,
          targetAnchor: Alignment.bottomLeft,
          followerAnchor: Alignment.topLeft,
          offset: const Offset(0, 4),
          child: UnconstrainedBox(
            // The overlay entry imposes the full overlay size; the dropdown
            // must size to its content instead.
            alignment: Alignment.topLeft,
            child: SizedBox(
              // Falls back to a sane width on the first frame, before the
              // trigger width has been measured.
              width: _overlayWidth ?? 320,
              child: Card(
                margin: EdgeInsets.zero,
                clipBehavior: Clip.hardEdge,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: TextField(
                        controller: _searchController,
                        autofocus: true,
                        decoration: InputDecoration(
                          hintText: getAttribute('hint'),
                          isDense: true,
                          border: const OutlineInputBorder(),
                        ),
                        onChanged: (query) => setState(() => _query = query),
                      ),
                    ),
                    SizedBox(
                      height: 280,
                      child: ListView(
                        children: [
                          for (var currency in filtered)
                            ListTile(
                              leading: _flag(currency['flag']),
                              title: Text(
                                currency['label'] ?? currency['value'] ?? '',
                              ),
                              onTap: () => _select(currency),
                            ),
                          if (filtered.isEmpty)
                            Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Text(
                                getAttribute('emptyLabel') ?? '',
                                textAlign: TextAlign.center,
                                style: Theme.of(context).textTheme.bodySmall,
                              ),
                            ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
      child: Align(
        // The parent (e.g. a Form filling the page) may impose tight
        // constraints; the target must hug the field so the dropdown
        // anchors right below it.
        alignment: Alignment.topCenter,
        child: CompositedTransformTarget(
          key: _targetKey,
          link: _link,
          child: InkWell(
            onTap: () {
              _overlayController.isShowing
                  ? _overlayController.hide()
                  : _overlayController.show();
            },
            child: InputDecorator(
              decoration: InputDecoration(
                labelText: getAttribute('label'),
                border: const OutlineInputBorder(),
              ),
              child: Row(
                children: [
                  _flag(selectedCurrency?['flag']),
                  const SizedBox(width: 12),
                  Expanded(child: Text(selectedCurrency?['label'] ?? '')),
                  const Icon(Icons.arrow_drop_down),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
