import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:liveview_flutter/live_view/live_view.dart';

import '../test_helpers.dart';

void main() {
  testWidgets('dropdown items generated by a comprehension are rendered', (
    tester,
  ) async {
    tester.setScreenSize(const Size(800, 800));

    var (view, _) = await connect(
      LiveView(),
      rendered: {
        '0': {
          's': ['<DropdownMenuItem', ' value="', '"></DropdownMenuItem>'],
          'd': [
            [' label="Bonus"', '1'],
            [' label="Intérêts"', '2'],
            [' label="Actions &amp; co"', '3'],
            [' label="Salaire"', '4'],
          ],
        },
        's': [
          """
        <flutter>
          <viewBody>
            <SingleChildScrollView>
              <Form phx-submit="save">
                <Column>
                  <DropdownButton name="transaction[category_id]" initialValue="" isExpanded="true">
                    <DropdownMenuItem label="No category" value="" />
                    [[flutterState key=0]]
                  </DropdownButton>
                  <ElevatedButton type="submit"><Text>Save</Text></ElevatedButton>
                </Column>
              </Form>
            </SingleChildScrollView>
          </viewBody>
        </flutter>
        """,
        ],
      },
    );

    await tester.runLiveView(view);
    await tester.pumpAndSettle();

    await tester.tap(find.byType(DropdownButton<String>));
    await tester.pumpAndSettle();

    expect(find.text('No category'), findsWidgets);
    expect(find.text('Bonus'), findsWidgets);
    expect(find.text('Intérêts'), findsWidgets);
    expect(find.text('Actions & co'), findsWidgets);
    expect(find.text('Salaire'), findsWidgets);
  });
}
